WarmodHeatStreetNavigation =
{
	 [1] =
	 {
	--	[129] = { "rightfence", "leftfence" },
	--	[128] = { "rightfence", "leftfence" },
	--	[97]  = { "rightfence", "leftfence" },
	--	[96]  = { "rightfence", "leftfence" },
	--	[93]  = { "rightfence", "leftfence" },
	--	[92]  = { "rightfence", "leftfence" },
	--	[56]  = { "rightfence", "leftfence" },
	--	[14]  = { "rightfence", "leftfence" },
	--	[13]  = { "rightfence", "leftfence" },
		-- каменные заборы
	--	[2]   = { "rightfence", "leftfence" },
		[5]   = {  "bswatshop", "bswatbeanch", "bswatrubish" },
		[6]   = {  "bswatshop", "bswatbeanch", "bswatrubish" },
		[53]  = {  "bswatshop", "bswatbeanch", "bswatrubish" },
		[7]   = {  "bswatshop", "bswatbeanch", "bswatrubish" },
		[18]  = { "bswatshop", "bswatbeanch", "bswatrubish" },
		[8]   = { "bswatshop", "bswatbeanch", "bswatrubish" },
		[26]  = { "bswatshop", "bswatbeanch", "bswatrubish", "bswatplywood" },
		[27]  = { "bswatshop", "bswatbeanch", "bswatrubish", "bswatplywood", "bswatcrossroads", "bswatfood" },
		[33]  = { "bswatshop", "bswatbeanch", "bswatrubish", "bswatplywood", "bswatcrossroads", "bswatfood" },
		[139] = { "bswatcrossroads" },
		[29]  = { "bswatfood", "bswatbooth" },
		[88]  = { "bswatbooth", "bswatfood" },
		[114] = { "bswatfood", "bswatforestofsteal2" },
		[156] = { "bswatforestofsteal", "bswatforestofsteal2" },
		[157] = { "bswatforestofsteal", "bswatforestofsteal2" },
		[28]  = { "bswatforestofsteal", "bswatforestofsteal2" },
		[30]  = { "bswatunderbridge", "bswatforestofsteal", "bswatforestofsteal2" },
		[36]  = { "bswatunderbridge", "bswatforestofsteal", "bswatforestofsteal2" },
		[37]  = { "bswatunderbridge", "bswatcrashred", "bswatcrashwhite", "crash33m" },
		[63]  = { "bswatcrashred", "bswatcrashwhite", "crash33m" },
		[38]  = { "crashfence",  "crash17m", "white16m", "bswatunderbridge", "bswatcrashwhite", "bswatcrashred" },
		[133] = { "bswatcrashred", "bswatcrashwhite", "crash33m" },
		[31]  = { "crashfence",  "crash17m", "white16m" },
		[58]  = { "crashfence",  "crash17m", "white16m", "bswatunderbridge", "bswatcrashwhite", "bswatcrashred" },
		[64]  = { "crash33m", "bswatunderbridge", "bswatcrashwhite", "bswatcrashred" },
		[34]  = { "bswatbooth", "bswatcrossroadsout", "bswatfood" },
		[127] = { "bswatbooth", "bswatcrossroadsout" },
		[134] = { "phase2wall", "bwall" },
		[123] = { "bswatfe", "bswatpbridge", "bswatbooth" },
		[79]  = { "bswatfe", "bswatpbridge", "phase2wall" },
		[124] = { "bswatfe", "bswatpbridge", "phase2wall" },
		[125] = { "bwall", "bswatfe", "bswatpbridge" },
		[126] = { "bwall","bswatfe", "bswatpbridge" },
		[142] = { "bwall", "bswatfe", "bswatpbridge" },
		[80]  = { "bwall","bswatfe", "bswatpbridge" },
		[99]  = { "bwall","bswatfe", "bswatpbridge" },
		[68]  = { "bwall","bswatfe", "bswatpbridge" },
		[52]  = { "bwall","bswatfe", "bswatpbridge" },
		[122] = { "bwall","bswatfe", "bswatpbridge" },
		[81]  = { "bswatbridgemid", "bswatstand", "bwall" },
		[140] = { "bswatfe" },
		[84]  = { "bswatbridgemid", "bswatstand", "bwall" },
		[82]  = { "bswatbridgemid", "bswatstand", "bwall" },
		[83]  = { "bswatblackf", "bswatredl", "bswatbridgemid" },
		[85]  = { "bswatglass", "bswatangle", "bswatbridgemid", "lastangle" },
		[86]  = { "bswatglass", "bswatangle", "bswatpbridge", "lastangle" },
		[87]  = { "bswatglass", "bswatangle", "bswatpbridge", "lastangle" },
		[65]  = { "bswatglass", "bswatangle", "bswatpbridge", "lastangle" },
		[132] = { "bswatglass", "bswatangle", "bswatpbridge", "lastangle" }		
	 },
	 [2] =
	 {
	 
	 }
};