WarmodCounterfeitNavigation = 
{
	[1] = {
		[21]  = { "RightHouseNear" },
		[106] = { "RightHouseNear" },
		[22]  = { "RightHouseNear", "LeftHouseNear" },
		[23]  = { "LeftHouseNear" },
		[107] = { "LeftHouseNear", "LeftHouseMiddle" },
		[33]  = { "LeftHouseNear", "LeftHouseMiddle" },
		[50]  = { "LeftHouseNear", "LeftHouseMiddle" },
		[108] = { "LeftHouseMiddle", "LeftBehindHouseFar", "CenterHouseMiddle" },
		[19]  = { "LeftHouseMiddle", "LeftBehindHouseFar", "CenterHouseMiddle" },
		[109] = { "LeftHouseMiddle", "LeftBehindHouseFar", "CenterHouseMiddle" },
		[48]  = { "CenterHouseMiddle", "LeftBehindHouseFar" },
		[25]  = { "CenterHouseMiddle", "RightHouseMiddle" },
		[110] = { "CenterHouseMiddle", "RightHouseMiddle" },
		[26]  = { "CenterHouseMiddle", "RightHouseMiddle" },
		[111] = { "CenterHouseMiddle", "RightHouseMiddle", "RightHouseNear" },
		[42]  = { "RightHouseMiddle", "RightHouseNear" },
		[133] = { "RightHouseMiddle", "RightHouseNear" },
		[105] = { "RightHouseMiddle", "RightHouseNear" },
		[30]  = { "RightHouseNear" },
		[38]  = { "RightHouseNear" },
		[2]   = { "RightHouseNear" },
		[1]   = { "RightHouseNear", "LeftHouseNear" },
		[112] = { "RightHouseMiddle", "RightHouseNear" },
		[3]   = { "RightHouseMiddle", "RightHouseNear" },
		[20]  = { "RightHouseMiddle", "RightHouseNear" },
		[61]  = { "RightHouseMiddle", "RightHouseNear" },
		[312] = { "RightHouseMiddle", "RightHouseNear" },
		[96]  = { "RightHouseMiddle", "RightHouseNear" },
		[43]  = { "RightHouseMiddle", "RightHouseNear", "CenterHouseMiddle" },
		[95]  = { "RightHouseMiddle", "RightHouseNear", "CenterHouseMiddle" },
		[356] = { "RightHouseMiddle", "RightHouseNear", "CenterHouseMiddle" },
		[44]  = { "RightHouseMiddle", "RightHouseNear", "CenterHouseMiddle" },
		[10]  = {"CenterHouseMiddle", "RightHouseMiddle" },
		[82]  = {"CenterHouseMiddle", "RightHouseMiddle" },
		-- дом
		[6]   = {"CenterHouseMiddle", "RightHouseMiddle" },
		[201] = {"CenterHouseMiddle", "RightHouseMiddle" },
		[7]   = {"CenterHouseMiddle", "RightHouseMiddle" },
		[75]  = {"CenterHouseMiddle", "RightHouseMiddle" },
		[66]  = {"CenterHouseMiddle", "RightHouseMiddle" },
		[37]  = {"CenterHouseMiddle", "RightHouseMiddle" },
		[80]  = {"CenterHouseMiddle", "RightHouseMiddle" },
		[5]   = {"CenterHouseMiddle", "RightHouseMiddle" },
		[8]   = {"CenterHouseMiddle", "RightHouseMiddle" },
		[9]   = {"CenterHouseMiddle", "RightHouseMiddle" },
		--
		[62]  = { "RightHouseNear", "LeftHouseNear" },
		[39]  = { "LeftHouseNear", "LeftHouseMiddle" },
		[32]  = { "LeftHouseNear", "LeftHouseMiddle" },
		[36]  = { "LeftHouseNear", "LeftHouseMiddle" },
		[0]   = { "LeftHouseNear", "LeftHouseMiddle" },
		[264] = { "LeftHouseNear", "LeftHouseMiddle" },
		[265] = { "LeftHouseNear", "LeftHouseMiddle" },
		[11]  = { "LeftHouseNear", "LeftHouseMiddle", "LeftBehindHouseFar", "CenterHouseMiddle" },
		[13]  = { "LeftHouseNear", "LeftHouseMiddle", "LeftBehindHouseFar", "CenterHouseMiddle" },
		[94]  = { "LeftHouseNear", "LeftHouseMiddle", "LeftBehindHouseFar", "CenterHouseMiddle" },
		[220] = { "LeftHouseMiddle", "LeftBehindHouseFar", "CenterHouseMiddle" },
		[14]  = { "LeftHouseMiddle", "LeftBehindHouseFar", "CenterHouseMiddle" },
		[15] = { "LeftHouseMiddle", "LeftBehindHouseFar", "CenterHouseMiddle" },
		[16] = { "LeftHouseMiddle", "LeftBehindHouseFar", "CenterHouseMiddle" },
		[56] = { "LeftHouseMiddle", "LeftBehindHouseFar", "CenterHouseMiddle" },
		[17] = { "CenterHouseMiddle" },
		[97] = { "CenterHouseMiddle" },
		[18] = { "CenterHouseMiddle" },
		[12] = { "CenterHouseMiddle", "LeftHouseMiddle" },
		[57] = { "CenterHouseMiddle", "LeftHouseMiddle" },
		[24] = { "LeftHouseNear", "LeftHouseMiddle", "LeftBehindHouseFar" },
		[47] = { "LeftHouseNear", "LeftHouseMiddle", "LeftBehindHouseFar", "CenterHouseMiddle" },
		[46] = { "LeftHouseMiddle", "LeftBehindHouseFar", "CenterHouseMiddle" },
		[49] = { "CenterHouseMiddle" },
		-- Подвал
		[40] = { "RightHouseMiddle", "RightHouseNear", "CenterHouseMiddle" },
		[4]  = { "RightHouseMiddle", "RightHouseNear", "CenterHouseMiddle" },
		[60] = { "RightHouseMiddle", "RightHouseNear", "CenterHouseMiddle" },
		[74] = { "RightHouseMiddle", "RightHouseNear", "CenterHouseMiddle", "LeftHouseNear", "LeftHouseMiddle" },
		[73] = { "RightHouseMiddle", "RightHouseNear", "CenterHouseMiddle", "LeftHouseNear", "LeftHouseMiddle" },
		[59] = { "RightHouseMiddle", "RightHouseNear", "CenterHouseMiddle", "LeftHouseNear", "LeftHouseMiddle" },
		[221] = { "RightHouseMiddle", "RightHouseNear", "CenterHouseMiddle", "LeftHouseNear", "LeftHouseMiddle" },
		[29] = { "RightHouseMiddle", "RightHouseNear", "CenterHouseMiddle", "LeftHouseNear", "LeftHouseMiddle" },
		[45] = { "RightHouseMiddle", "RightHouseNear", "CenterHouseMiddle", "LeftHouseNear", "LeftHouseMiddle" },
		[357] = { "RightHouseMiddle", "RightHouseNear", "CenterHouseMiddle", "LeftHouseNear", "LeftHouseMiddle" },
		[222] = { "RightHouseMiddle", "RightHouseNear", "CenterHouseMiddle", "LeftHouseNear", "LeftHouseMiddle" },
		[58]  = { "RightHouseMiddle", "RightHouseNear", "CenterHouseMiddle", "LeftHouseNear", "LeftHouseMiddle" },
		[28]  = { "CenterHouseMiddle", "LeftHouseNear", "LeftHouseMiddle" },
		[72]  = { "CenterHouseMiddle", "LeftHouseNear", "LeftHouseMiddle" },
		[27]  = { "CenterHouseMiddle", "LeftHouseNear", "LeftHouseMiddle" }
	},
	[2] = {
		-- Дальняя канализация
		[153] = { "LongPipe", "MiddleVent", "LongVent", "NearVent", "RightHouseMiddle", "RightHouseNear", "CenterHouseMiddle", "LeftHouseNear", "LeftHouseMiddle", "LeftBehindHouseFar" },
		[154] = { "LongPipe", "MiddleVent", "LongVent", "NearVent", "RightHouseMiddle", "RightHouseNear", "CenterHouseMiddle", "LeftHouseNear", "LeftHouseMiddle", "LeftBehindHouseFar" },
		[155] = { "LongPipe", "MiddleVent", "LongVent", "NearVent", "RightHouseMiddle", "RightHouseNear", "CenterHouseMiddle", "LeftHouseNear", "LeftHouseMiddle", "LeftBehindHouseFar" },
		[156] = { "LongPipe", "MiddleVent", "LongVent", "NearVent", "RightHouseMiddle", "RightHouseNear", "CenterHouseMiddle", "LeftHouseNear", "LeftHouseMiddle", "LeftBehindHouseFar" },
		[157] = { "LongPipe", "MiddleVent", "LongVent", "NearVent", "RightHouseMiddle", "RightHouseNear", "CenterHouseMiddle", "LeftHouseNear", "LeftHouseMiddle", "LeftBehindHouseFar" },
		[158] = { "LongPipe", "MiddleVent", "LongVent", "NearVent", "RightHouseMiddle", "RightHouseNear", "CenterHouseMiddle", "LeftHouseNear", "LeftHouseMiddle", "LeftBehindHouseFar" },
		[159] = { "LongPipe", "MiddleVent", "LongVent", "NearVent", "RightHouseMiddle", "RightHouseNear", "CenterHouseMiddle", "LeftHouseNear", "LeftHouseMiddle", "LeftBehindHouseFar" },
		[160] = { "LongPipe", "MiddleVent", "LongVent", "NearVent", "RightHouseMiddle", "RightHouseNear", "CenterHouseMiddle", "LeftHouseNear", "LeftHouseMiddle", "LeftBehindHouseFar" },
		-- Ближняя канализация
		[163] = { "LongPipe", "MiddleVent", "LongVent", "NearVent", "RightHouseMiddle", "RightHouseNear", "CenterHouseMiddle", "LeftHouseNear", "LeftHouseMiddle", "LeftBehindHouseFar" },
		[162] = { "LongPipe", "MiddleVent", "LongVent", "NearVent", "RightHouseMiddle", "RightHouseNear", "CenterHouseMiddle", "LeftHouseNear", "LeftHouseMiddle", "LeftBehindHouseFar" },
		[161] = { "LongPipe", "MiddleVent", "LongVent", "NearVent", "RightHouseMiddle", "RightHouseNear", "CenterHouseMiddle", "LeftHouseNear", "LeftHouseMiddle", "LeftBehindHouseFar" },
		[151] = { "LongPipe", "MiddleVent", "LongVent", "NearVent", "RightHouseMiddle", "RightHouseNear", "CenterHouseMiddle", "LeftHouseNear", "LeftHouseMiddle", "LeftBehindHouseFar" },
		[152] = { "LongPipe", "MiddleVent", "LongVent", "NearVent", "RightHouseMiddle", "RightHouseNear", "CenterHouseMiddle", "LeftHouseNear", "LeftHouseMiddle", "LeftBehindHouseFar" },
		[150] = { "LongPipe", "MiddleVent", "LongVent", "NearVent", "RightHouseMiddle", "RightHouseNear", "CenterHouseMiddle", "LeftHouseNear", "LeftHouseMiddle", "LeftBehindHouseFar" },
		
		--
		-- Подвал побег
		[40] = { "LongPipe", "MiddleVent", "LongVent", "NearVent", "RightHouseMiddle", "RightHouseNear", "CenterHouseMiddle" },
		[4]  = { "LongPipe", "MiddleVent", "LongVent", "NearVent", "RightHouseMiddle", "RightHouseNear", "CenterHouseMiddle" },
		[60] = { "LongPipe", "MiddleVent", "LongVent", "NearVent", "RightHouseMiddle", "RightHouseNear", "CenterHouseMiddle" },
		[74] = { "LongPipe", "MiddleVent", "LongVent", "NearVent", "RightHouseMiddle", "RightHouseNear", "CenterHouseMiddle" },
		[73] = { "LongPipe", "MiddleVent", "LongVent", "NearVent", "RightHouseMiddle", "RightHouseNear", "CenterHouseMiddle" },
		[59] = { "LongPipe", "MiddleVent", "LongVent", "NearVent", "RightHouseMiddle", "RightHouseNear", "CenterHouseMiddle" },
		[221] = { "LongPipe", "MiddleVent", "LongVent", "NearVent", "RightHouseMiddle", "RightHouseNear", "CenterHouseMiddle" },
		[29] = { "LongPipe", "MiddleVent", "LongVent", "NearVent", "RightHouseMiddle", "RightHouseNear", "CenterHouseMiddle" },
		[45] = { "LongPipe", "MiddleVent", "LongVent", "NearVent", "RightHouseMiddle", "RightHouseNear", "CenterHouseMiddle" },
		[357] = { "LongPipe", "MiddleVent", "LongVent", "NearVent", "RightHouseMiddle", "RightHouseNear", "CenterHouseMiddle" },
		[222] = { "LongPipe", "MiddleVent", "LongVent", "NearVent", "RightHouseMiddle", "RightHouseNear", "CenterHouseMiddle" },
		[58]  = { "LongPipe", "MiddleVent", "LongVent", "NearVent", "RightHouseMiddle", "RightHouseNear", "CenterHouseMiddle" },
		[28]  = { "LongPipe", "MiddleVent", "LongVent", "NearVent", "RightHouseMiddle", "RightHouseNear", "CenterHouseMiddle" },
		[72]  = { "LongPipe", "MiddleVent", "LongVent", "NearVent", "RightHouseMiddle", "RightHouseNear", "CenterHouseMiddle" },
		[27]  = { "LongPipe", "MiddleVent", "LongVent", "NearVent", "RightHouseMiddle", "RightHouseNear", "CenterHouseMiddle" }
	}
};