SpawnList =
{
	WSec1	= 
	{
		WSec1	= true,
		WSec2	= true,
		RSec	= false,
		
		Murky1	= false,
		Murky2	= false,	

		Cop1 	= false,
		Cop2	= false,
		Cop3	= false,
		Fbi1	= false,
		Fbi2	= false,
		Fbi3	= false,
		Swat1	= false,
		Swat2	= false,
		Swat3	= false,
		BSwat1	= false,
		BSwat2	= false,
		Cloaker	= false,
		Taser	= false,
		Shield	= false,
		BDozer	= false,
		Sniper	= false	
	},
	WSec2	= 
	{
		WSec1	= true,
		WSec2	= true,
		RSec	= false,
		
		Murky1	= false,
		Murky2	= false,	

		Cop1 	= false,
		Cop2	= false,
		Cop3	= false,
		Fbi1	= false,
		Fbi2	= false,
		Fbi3	= false,
		Swat1	= false,
		Swat2	= false,
		Swat3	= false,
		BSwat1	= false,
		BSwat2	= false,
		Cloaker	= false,
		Taser	= false,
		Shield	= false,
		BDozer	= false,
		Sniper	= false				
	},
	RSec	= 
	{
		WSec1	= false,
		WSec2	= false,
		RSec	= true,

		Cop1 	= false,
		Cop2	= false,
		Cop3	= false,
		Fbi1	= false,
		Fbi2	= false,
		Fbi3	= false,
		Swat1	= false,
		Swat2	= false,
		Swat3	= false,
		BSwat1	= false,
		BSwat2	= false,
		Cloaker	= false,
		Taser	= false,
		Shield	= false,
		BDozer	= false,
		Sniper	= false			
	},
	
	Gang1	=
	{
		Gang1	= true,
		Gang2	= true,
		Gang3	= true,
		Gang4	= true,
		Gang5	= true,
		Gang6	= true,
		Dealer	= true,

		Cop1 	= false,
		Cop2	= false,
		Cop3	= false,
		Fbi1	= false,
		Fbi2	= false,
		Fbi3	= false,
		Swat1	= false,
		Swat2	= false,
		Swat3	= false,
		BSwat1	= false,
		BSwat2	= false,
		Cloaker	= false,
		Taser	= false,
		Shield	= false,
		BDozer	= false,
		Sniper	= false		
	},
	Gang2	= 
	{
		Gang1	= true,
		Gang2	= true,
		Gang3	= true,
		Gang4	= true,
		Gang5	= true,
		Gang6	= true,
		Dealer	= true,

		Cop1 	= false,
		Cop2	= false,
		Cop3	= false,
		Fbi1	= false,
		Fbi2	= false,
		Fbi3	= false,
		Swat1	= false,
		Swat2	= false,
		Swat3	= false,
		BSwat1	= false,
		BSwat2	= false,
		Cloaker	= false,
		Taser	= false,
		Shield	= false,
		BDozer	= false,
		Sniper	= false			
	},		
	Gang3	= 
	{
		Gang1	= true,
		Gang2	= true,
		Gang3	= true,
		Gang4	= true,
		Gang5	= true,
		Gang6	= true,
		Dealer	= true,

		Cop1 	= false,
		Cop2	= false,
		Cop3	= false,
		Fbi1	= false,
		Fbi2	= false,
		Fbi3	= false,
		Swat1	= false,
		Swat2	= false,
		Swat3	= false,
		BSwat1	= false,
		BSwat2	= false,
		Cloaker	= false,
		Taser	= false,
		Shield	= false,
		BDozer	= false,
		Sniper	= false		
	},
	Gang4	= 
	{
		Gang1	= true,
		Gang2	= true,
		Gang3	= true,
		Gang4	= true,
		Gang5	= true,
		Gang6	= true,
		Dealer	= true,

		Cop1 	= false,
		Cop2	= false,
		Cop3	= false,
		Fbi1	= false,
		Fbi2	= false,
		Fbi3	= false,
		Swat1	= false,
		Swat2	= false,
		Swat3	= false,
		BSwat1	= false,
		BSwat2	= false,
		Cloaker	= false,
		Taser	= false,
		Shield	= false,
		BDozer	= false,
		Sniper	= false		
	},
	Gang5	= 
	{
		Gang1	= true,
		Gang2	= true,
		Gang3	= true,
		Gang4	= true,
		Gang5	= true,
		Gang6	= true,
		Dealer	= true,

		Cop1 	= false,
		Cop2	= false,
		Cop3	= false,
		Fbi1	= false,
		Fbi2	= false,
		Fbi3	= false,
		Swat1	= false,
		Swat2	= false,
		Swat3	= false,
		BSwat1	= false,
		BSwat2	= false,
		Cloaker	= false,
		Taser	= false,
		Shield	= false,
		BDozer	= false,
		Sniper	= false		
	},
	Gang6	= 
	{
		Gang1	= true,
		Gang2	= true,
		Gang3	= true,
		Gang4	= true,
		Gang5	= true,
		Gang6	= true,
		Dealer	= true,

		Cop1 	= false,
		Cop2	= false,
		Cop3	= false,
		Fbi1	= false,
		Fbi2	= false,
		Fbi3	= false,
		Swat1	= false,
		Swat2	= false,
		Swat3	= false,
		BSwat1	= false,
		BSwat2	= false,
		Cloaker	= false,
		Taser	= false,
		Shield	= false,
		BDozer	= false,
		Sniper	= false			
	},
	Dealer	= 
	{
		Gang1	= true,
		Gang2	= true,
		Gang3	= true,
		Gang4	= true,
		Gang5	= true,
		Gang6	= true,
		Dealer	= true,

		Cop1 	= false,
		Cop2	= false,
		Cop3	= false,
		Fbi1	= false,
		Fbi2	= false,
		Fbi3	= false,
		Swat1	= false,
		Swat2	= false,
		Swat3	= false,
		BSwat1	= false,
		BSwat2	= false,
		Cloaker	= false,
		Taser	= false,
		Shield	= false,
		BDozer	= false,
		Sniper	= false		
	},
	
	Murky1	= 
	{
		WSec1	= false,
		WSec2	= false,
		
		Murky1	= true,
		Murky2	= true,	

		Cop1 	= false,
		Cop2	= false,
		Cop3	= false,
		Fbi1	= false,
		Fbi2	= false,
		Fbi3	= false,
		Swat1	= false,
		Swat2	= false,
		Swat3	= false,
		BSwat1	= false,
		BSwat2	= false,
		Cloaker	= false,
		Taser	= false,
		Shield	= false,
		BDozer	= false,
		Sniper	= false		
	},
	Murky2	=
	{
		WSec1	= false,
		WSec2	= false,
		
		Murky1	= true,
		Murky2	= true,	

		Cop1 	= false,
		Cop2	= false,
		Cop3	= false,
		Fbi1	= false,
		Fbi2	= false,
		Fbi3	= false,
		Swat1	= false,
		Swat2	= false,
		Swat3	= false,
		BSwat1	= false,
		BSwat2	= false,
		Cloaker	= false,
		Taser	= false,
		Shield	= false,
		BDozer	= false,
		Sniper	= false		
	},

	Cop1 	= 
	{
		WSec1	= false,
		WSec2	= false,
		RSec	= false,
		
		Murky1	= false,
		Murky2	= false,

		Gang1	= false,
		Gang2	= false,
		Gang3	= false,
		Gang4	= false,
		Gang5	= false,
		Gang6	= false,
		Dealer	= false,			

		Cop1 	= false,
		Cop2	= false,
		Cop3	= false,
		Fbi1	= false,
		Fbi2	= false,
		Fbi3	= false,
		Swat1	= false,
		Swat2	= false,
		Swat3	= false,
		BSwat1	= true,
		BSwat2	= true,
		Cloaker	= false,
		Taser	= false,
		Shield	= false,
		BDozer	= false,
		Sniper	= false			
	},
	Cop2	= 
	{
		WSec1	= false,
		WSec2	= false,
		RSec	= false,
		
		Murky1	= false,
		Murky2	= false,

		Gang1	= false,
		Gang2	= false,
		Gang3	= false,
		Gang4	= false,
		Gang5	= false,
		Gang6	= false,
		Dealer	= false,			

		Cop1 	= false,
		Cop2	= false,
		Cop3	= false,
		Fbi1	= false,
		Fbi2	= false,
		Fbi3	= false,
		Swat1	= false,
		Swat2	= false,
		Swat3	= false,
		BSwat1	= true,
		BSwat2	= true,
		Cloaker	= false,
		Taser	= false,
		Shield	= false,
		BDozer	= false,
		Sniper	= false			
	},		
	Cop3	= 
	{
		WSec1	= false,
		WSec2	= false,
		RSec	= false,
		
		Murky1	= false,
		Murky2	= false,

		Gang1	= false,
		Gang2	= false,
		Gang3	= false,
		Gang4	= false,
		Gang5	= false,
		Gang6	= false,
		Dealer	= false,			

		Cop1 	= false,
		Cop2	= false,
		Cop3	= false,
		Fbi1	= false,
		Fbi2	= false,
		Fbi3	= false,
		Swat1	= false,
		Swat2	= false,
		Swat3	= false,
		BSwat1	= true,
		BSwat2	= true,
		Cloaker	= false,
		Taser	= false,
		Shield	= false,
		BDozer	= false,
		Sniper	= false			
	},
	Fbi1	= 
	{
		WSec1	= false,
		WSec2	= false,
		RSec	= false,
		
		Murky1	= false,
		Murky2	= false,

		Gang1	= false,
		Gang2	= false,
		Gang3	= false,
		Gang4	= false,
		Gang5	= false,
		Gang6	= false,
		Dealer	= false,			

		Cop1 	= false,
		Cop2	= false,
		Cop3	= false,
		Fbi1	= false,
		Fbi2	= false,
		Fbi3	= false,
		Swat1	= false,
		Swat2	= false,
		Swat3	= false,
		BSwat1	= true,
		BSwat2	= true,
		Cloaker	= false,
		Taser	= false,
		Shield	= false,
		BDozer	= false,
		Sniper	= true			
	},
	Fbi2	= 
	{
		WSec1	= false,
		WSec2	= false,
		RSec	= false,
		
		Murky1	= false,
		Murky2	= false,

		Gang1	= false,
		Gang2	= false,
		Gang3	= false,
		Gang4	= false,
		Gang5	= false,
		Gang6	= false,
		Dealer	= false,			

		Cop1 	= false,
		Cop2	= false,
		Cop3	= false,
		Fbi1	= false,
		Fbi2	= false,
		Fbi3	= false,
		Swat1	= false,
		Swat2	= false,
		Swat3	= false,
		BSwat1	= true,
		BSwat2	= true,
		Cloaker	= false,
		Taser	= false,
		Shield	= false,
		BDozer	= false,
		Sniper	= true			
	},
	Fbi3	= 
	{
		WSec1	= false,
		WSec2	= false,
		RSec	= false,
		
		Murky1	= false,
		Murky2	= false,

		Gang1	= false,
		Gang2	= false,
		Gang3	= false,
		Gang4	= false,
		Gang5	= false,
		Gang6	= false,
		Dealer	= false,			

		Cop1 	= false,
		Cop2	= false,
		Cop3	= false,
		Fbi1	= false,
		Fbi2	= false,
		Fbi3	= false,
		Swat1	= false,
		Swat2	= false,
		Swat3	= false,
		BSwat1	= true,
		BSwat2	= true,
		Cloaker	= false,
		Taser	= false,
		Shield	= false,
		BDozer	= false,
		Sniper	= true				
	},
	Swat1	= 
	{
		WSec1	= false,
		WSec2	= false,
		RSec	= false,
		
		Murky1	= false,
		Murky2	= false,

		Gang1	= false,
		Gang2	= false,
		Gang3	= false,
		Gang4	= false,
		Gang5	= false,
		Gang6	= false,
		Dealer	= false,			

		Cop1 	= false,
		Cop2	= false,
		Cop3	= false,
		Fbi1	= false,
		Fbi2	= false,
		Fbi3	= false,
		Swat1	= false,
		Swat2	= false,
		Swat3	= false,
		BSwat1	= true,
		BSwat2	= true,
		Cloaker	= false,
		Taser	= false,
		Shield	= false,
		BDozer	= false,
		Sniper	= true				
	},
	Swat2	= 
	{
		WSec1	= false,
		WSec2	= false,
		RSec	= false,
		
		Murky1	= false,
		Murky2	= false,

		Gang1	= false,
		Gang2	= false,
		Gang3	= false,
		Gang4	= false,
		Gang5	= false,
		Gang6	= false,
		Dealer	= false,			

		Cop1 	= false,
		Cop2	= false,
		Cop3	= false,
		Fbi1	= false,
		Fbi2	= false,
		Fbi3	= false,
		Swat1	= false,
		Swat2	= false,
		Swat3	= false,
		BSwat1	= true,
		BSwat2	= true,
		Cloaker	= false,
		Taser	= false,
		Shield	= false,
		BDozer	= false,
		Sniper	= true				
	},
	Swat3	= 
	{
		WSec1	= false,
		WSec2	= false,
		RSec	= false,
		
		Murky1	= false,
		Murky2	= false,

		Gang1	= false,
		Gang2	= false,
		Gang3	= false,
		Gang4	= false,
		Gang5	= false,
		Gang6	= false,
		Dealer	= false,			

		Cop1 	= false,
		Cop2	= false,
		Cop3	= false,
		Fbi1	= false,
		Fbi2	= false,
		Fbi3	= false,
		Swat1	= false,
		Swat2	= false,
		Swat3	= false,
		BSwat1	= true,
		BSwat2	= true,
		Cloaker	= false,
		Taser	= false,
		Shield	= false,
		BDozer	= false,
		Sniper	= true			
	},
	BSwat1	= 
	{
		WSec1	= false,
		WSec2	= false,
		RSec	= false,
		
		Murky1	= false,
		Murky2	= false,

		Gang1	= false,
		Gang2	= false,
		Gang3	= false,
		Gang4	= false,
		Gang5	= false,
		Gang6	= false,
		Dealer	= false,			

		Cop1 	= false,
		Cop2	= false,
		Cop3	= false,
		Fbi1	= false,
		Fbi2	= false,
		Fbi3	= false,
		Swat1	= false,
		Swat2	= false,
		Swat3	= false,
		BSwat1	= true,
		BSwat2	= false,
		Cloaker	= false,
		Taser	= false,
		Shield	= false,
		BDozer	= false,
		Sniper	= false				
	},
	BSwat2	= 
	{
		WSec1	= false,
		WSec2	= false,
		RSec	= false,
		
		Murky1	= false,
		Murky2	= false,

		Gang1	= false,
		Gang2	= false,
		Gang3	= false,
		Gang4	= false,
		Gang5	= false,
		Gang6	= false,
		Dealer	= false,			

		Cop1 	= false,
		Cop2	= false,
		Cop3	= false,
		Fbi1	= false,
		Fbi2	= false,
		Fbi3	= false,
		Swat1	= false,
		Swat2	= false,
		Swat3	= false,
		BSwat1	= false,
		BSwat2	= true,
		Cloaker	= false,
		Taser	= false,
		Shield	= false,
		BDozer	= false,
		Sniper	= false				
	},
	Cloaker	= 
	{
		WSec1	= false,
		WSec2	= false,
		RSec	= false,
		
		Murky1	= false,
		Murky2	= false,

		Gang1	= false,
		Gang2	= false,
		Gang3	= false,
		Gang4	= false,
		Gang5	= false,
		Gang6	= false,
		Dealer	= false,			

		Cop1 	= false,
		Cop2	= false,
		Cop3	= false,
		Fbi1	= false,
		Fbi2	= false,
		Fbi3	= false,
		Swat1	= false,
		Swat2	= false,
		Swat3	= false,
		BSwat1	= false,
		BSwat2	= false,
		Cloaker	= true,
		Taser	= false,
		Shield	= false,
		BDozer	= false,
		Sniper	= false				
	},
	Taser	= 
	{
		WSec1	= false,
		WSec2	= false,
		RSec	= false,
		
		Murky1	= false,
		Murky2	= false,

		Gang1	= false,
		Gang2	= false,
		Gang3	= false,
		Gang4	= false,
		Gang5	= false,
		Gang6	= false,
		Dealer	= false,			

		Cop1 	= false,
		Cop2	= false,
		Cop3	= false,
		Fbi1	= false,
		Fbi2	= false,
		Fbi3	= false,
		Swat1	= false,
		Swat2	= false,
		Swat3	= false,
		BSwat1	= false,
		BSwat2	= false,
		Cloaker	= false,
		Taser	= true,
		Shield	= true,
		BDozer	= true,
		Sniper	= false			
	},
	Shield	= 
	{
		WSec1	= false,
		WSec2	= false,
		RSec	= false,
		
		Murky1	= false,
		Murky2	= false,

		Gang1	= false,
		Gang2	= false,
		Gang3	= false,
		Gang4	= false,
		Gang5	= false,
		Gang6	= false,
		Dealer	= false,			

		Cop1 	= false,
		Cop2	= false,
		Cop3	= false,
		Fbi1	= false,
		Fbi2	= false,
		Fbi3	= false,
		Swat1	= false,
		Swat2	= false,
		Swat3	= false,
		BSwat1	= false,
		BSwat2	= false,
		Cloaker	= false,
		Taser	= false,
		Shield	= true,
		BDozer	= false,
		Sniper	= true			
	},
	BDozer	= 
	{
		WSec1	= false,
		WSec2	= false,
		RSec	= false,
		
		Murky1	= false,
		Murky2	= false,

		Gang1	= false,
		Gang2	= false,
		Gang3	= false,
		Gang4	= false,
		Gang5	= false,
		Gang6	= false,
		Dealer	= false,			

		Cop1 	= false,
		Cop2	= false,
		Cop3	= false,
		Fbi1	= false,
		Fbi2	= false,
		Fbi3	= false,
		Swat1	= false,
		Swat2	= false,
		Swat3	= false,
		BSwat1	= false,
		BSwat2	= false,
		Cloaker	= false,
		Taser	= false,
		Shield	= true,
		BDozer	= true,
		Sniper	= false			
	},
	Sniper	= 
	{
		WSec1	= false,
		WSec2	= false,
		RSec	= false,
		
		Murky1	= false,
		Murky2	= false,

		Gang1	= false,
		Gang2	= false,
		Gang3	= false,
		Gang4	= false,
		Gang5	= false,
		Gang6	= false,
		Dealer	= false,			

		Cop1 	= false,
		Cop2	= false,
		Cop3	= false,
		Fbi1	= false,
		Fbi2	= false,
		Fbi3	= false,
		Swat1	= false,
		Swat2	= false,
		Swat3	= false,
		BSwat1	= false,
		BSwat2	= false,
		Cloaker	= false,
		Taser	= false,
		Shield	= false,
		BDozer	= false,
		Sniper	= true			
	}
}